name: dprv2
channels:
  - bioconda
  - pytorch
  - bioconda
  - main
  - conda-forge
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - abseil-cpp=20211102.0=h27087fc_1
  - antlr-python-runtime=4.9.3=pyhd8ed1ab_1
  - anyio=3.7.1=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - arrow=1.3.0=pyhd8ed1ab_0
  - arrow-cpp=11.0.0=h374c478_2
  - attrs=23.1.0=pyh71513ae_1
  - aws-c-common=0.6.8=h5eee18b_1
  - aws-c-event-stream=0.1.6=h6a678d5_6
  - aws-checksums=0.1.11=h5eee18b_2
  - aws-sdk-cpp=1.8.185=h721c034_1
  - backoff=2.2.1=pyhd8ed1ab_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - biopython=1.79=py39h3811e60_1
  - blas=1.0=mkl
  - blessed=1.19.1=pyhe4f9e05_2
  - boost-cpp=1.78.0=he72f1d9_0
  - boto3=1.28.78=pyhd8ed1ab_0
  - botocore=1.31.78=pyhd8ed1ab_0
  - bottleneck=1.3.5=py39h7deecbd_0
  - brotli-python=1.0.9=py39h6a678d5_7
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2023.12.12=h06a4308_0
  - cachecontrol=0.12.11=py39h06a4308_1
  - certifi=2024.2.2=py39h06a4308_0
  - cffi=1.15.1=py39h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cleo=2.0.1=py39h06a4308_0
  - click=8.1.7=unix_pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - crashtest=0.4.1=pyhd8ed1ab_0
  - croniter=1.4.1=pyhd8ed1ab_0
  - cryptography=41.0.3=py39hdda0065_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - dateutils=0.6.12=py_0
  - dbus=1.13.6=he372182_0
  - deepdiff=5.8.1=pyhd8ed1ab_0
  - dendropy=4.6.1=pyhdfd78af_0
  - distlib=0.3.7=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=py_0
  - dulwich=0.21.3=py39h5eee18b_0
  - exceptiongroup=1.1.3=pyhd8ed1ab_0
  - expat=2.2.10=h9c3ff4c_0
  - faiss-cpu=1.7.4=py3.9_h8c27c75_0_cpu
  - fastapi=0.103.2=pyhd8ed1ab_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=pyhd8ed1ab_0
  - freetype=2.12.1=h4a9f257_0
  - fsspec=2023.10.0=pyhca7485f_0
  - gawk=5.1.0=h7b6447c_0
  - gflags=2.2.2=he1b5a44_1004
  - giflib=5.2.1=h5eee18b_3
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.40=pyhd8ed1ab_0
  - glib=2.69.1=he621ea3_2
  - glog=0.5.0=h48cff8f_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - grpc-cpp=1.48.2=he1ff14a_1
  - h11=0.14.0=pyhd8ed1ab_0
  - hmmer=3.1b2=3
  - html5lib=1.1=pyh9f0ad1d_0
  - hydra-core=1.3.2=pyhd8ed1ab_0
  - icu=70.1=h27087fc_0
  - idna=3.4=py39h06a4308_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - importlib_resources=6.1.0=pyhd8ed1ab_0
  - inquirer=3.1.3=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - itsdangerous=2.1.2=pyhd8ed1ab_0
  - jaraco.classes=3.3.0=pyhd8ed1ab_0
  - jeepney=0.8.0=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jmespath=1.0.1=pyhd8ed1ab_0
  - jpeg=9e=h5eee18b_1
  - jsonschema=4.19.2=pyhd8ed1ab_0
  - jsonschema-specifications=2023.7.1=pyhd8ed1ab_0
  - keyring=23.13.1=py39hf3d152e_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcurl=8.4.0=h251f7ec_0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h516909a_1
  - libevent=2.1.12=hdbd6064_1
  - libfaiss=1.7.4=h2bc3f7f_0_cpu
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=3.20.3=he621ea3_0
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - lightning=2.1.0=pyhd8ed1ab_0
  - lightning-cloud=0.5.49=pyhd8ed1ab_0
  - lightning-utilities=0.9.0=pyhd8ed1ab_0
  - lockfile=0.12.2=py_1
  - lz4-c=1.9.4=h6a678d5_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.1=py39h7f8727e_0
  - mdurl=0.1.0=pyhd8ed1ab_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - mmseqs2=13.45111=h95f258a_1
  - more-itertools=10.1.0=pyhd8ed1ab_0
  - msgpack-python=1.0.3=py39hd09550d_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - numexpr=2.8.4=py39he184ba9_0
  - numpy=1.24.3=py39h14f4228_0
  - numpy-base=1.24.3=py39h31eccc5_0
  - omegaconf=2.3.0=pyhd8ed1ab_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.13=h7f8727e_0
  - orc=1.7.4=hb3bc3d3_1
  - ordered-set=4.1.0=pyhd8ed1ab_0
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=2.1.1=py39h1128e8f_0
  - pandas-flavor=0.6.0=pyhd8ed1ab_1
  - pathtools=0.1.2=py_1
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pillow=10.0.1=py39ha6cbd5a_0
  - pip=23.3=py39h06a4308_0
  - pkginfo=1.9.6=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=2.5.2=py39h06a4308_0
  - poetry=1.4.0=py39h06a4308_0
  - poetry-core=1.5.1=py39h06a4308_0
  - poetry-plugin-export=1.3.0=py39h4849bfd_0
  - protobuf=3.20.3=py39h6a678d5_0
  - psutil=5.9.0=py39h5eee18b_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pyarrow=11.0.0=py39h468efa6_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=1.10.12=py39h5eee18b_1
  - pygments=2.16.1=pyhd8ed1ab_0
  - pyjwt=2.8.0=pyhd8ed1ab_0
  - pyopenssl=23.2.0=py39h06a4308_0
  - pyproject_hooks=1.0.0=pyhd8ed1ab_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.18=h955ad1f_0
  - python-build=0.10.0=py39h06a4308_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-editor=1.0.4=py_0
  - python-installer=0.6.0=py39h06a4308_0
  - python-multipart=0.0.6=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytorch=1.12.0=py3.9_cuda11.3_cudnn8.3.2_0
  - pytorch-lightning=2.1.0=pyhd8ed1ab_0
  - pytorch-mutex=1.0=cuda
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pyyaml=6.0=py39hb9d737c_4
  - rapidfuzz=2.13.7=py39h417a72b_0
  - re2=2022.04.01=h27087fc_0
  - readchar=4.0.5=pyhd8ed1ab_0
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=pyhd8ed1ab_0
  - requests=2.31.0=py39h06a4308_0
  - requests-toolbelt=0.10.1=pyhd8ed1ab_0
  - rich=13.6.0=pyhd8ed1ab_0
  - rpds-py=0.10.6=py39hb02cf49_0
  - s3transfer=0.7.0=pyhd8ed1ab_0
  - secretstorage=3.3.3=py39hf3d152e_2
  - sentry-sdk=1.34.0=pyhd8ed1ab_0
  - setproctitle=1.1.10=py39h3811e60_1004
  - setuptools=68.0.0=py39h06a4308_0
  - shellingham=1.5.4=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - snappy=1.1.9=h295c915_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sqlite=3.41.2=h5eee18b_0
  - starlette=0.27.0=pyhd8ed1ab_0
  - starsessions=1.3.0=pyhd8ed1ab_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomlkit=0.12.2=pyha770c72_0
  - torchaudio=0.12.0=py39_cu113
  - torchmetrics=1.2.0=pyhd8ed1ab_0
  - torchvision=0.13.0=py39_cu113
  - tqdm=4.65.0=py39hb070fc8_0
  - traitlets=5.13.0=pyhd8ed1ab_0
  - trove-classifiers=2023.10.18=pyhd8ed1ab_0
  - types-python-dateutil=2.8.19.14=pyhd8ed1ab_0
  - typing-extensions=4.7.1=py39h06a4308_0
  - typing_extensions=4.7.1=py39h06a4308_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.18=py39h06a4308_0
  - utf8proc=2.6.1=h27cfd23_0
  - uvicorn=0.23.2=py39hf3d152e_1
  - virtualenv=20.17.1=py39hf3d152e_0
  - wandb=0.15.12=pyhd8ed1ab_0
  - wcwidth=0.2.9=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.6.4=pyhd8ed1ab_0
  - websockets=10.4=py39h5eee18b_1
  - wget=1.20.3=ha35d2d1_1
  - wheel=0.41.2=py39h06a4308_0
  - xarray=2023.10.1=pyhd8ed1ab_0
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7f98852_2
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - absl-py==2.0.0
      - aiohttp==3.8.6
      - aiosignal==1.3.1
      - async-timeout==4.0.3
      - contextlib2==21.6.0
      - deepspeed==0.5.9
      - dm-tree==0.1.8
      - einops==0.7.0
      - fair-esm==2.0.0
      - frozenlist==1.4.0
      - hjson==3.1.0
      - ml-collections==0.1.1
      - multidict==6.0.4
      - ninja==1.11.1.1
      - py-cpuinfo==9.0.0
      - scipy==1.11.3
      - yarl==1.9.2
